# Generated by Django 4.2.7 on 2024-05-30 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Payment_methos',
            new_name='Payment_method',
        ),
    ]
