# Generated by Django 4.2.7 on 2024-05-31 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_payment_methos_payment_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Payment',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='orderedfood',
            old_name='Payment',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Payment_method',
            new_name='payment_method',
        ),
    ]
